apply plugin: 'jacoco'

def coverageExclusions = [
        "**/R.class",
        "**/R\$*.class",
        "**/BuildConfig.*",
        "**/Manifest*.*",
        "android/**/*.*",
        // Hilt/Dagger
        "**/di/*.*",
        "**/databinding/**",
        "**/Dagger*Component*.*",
        "**/*_Hilt*.class",
        "**/Hilt_*.class",
        "**/*_HiltModules*.*",
        "**/*_ComponentTreeDeps*.*",
        "**/*_GeneratedInjector*.*",
        "**/hilt_aggregated_deps/**",
        "**/*_Factory.*",
        "**/*_MembersInjector.*",
        // Room
        "**/*_Impl.*",
        "**/*_Dai_Impl.*",
        "**/databinding/*",
        "**/BR.*",
        // Navigation
        "**/Directions*.*",
        "**/*Args*.*",
]

tasks.register("jacocoTestReport", JacocoReport) {
    dependsOn "testDebugUnitTest"
    group = "Reporting"
    description = "Generate Jacoco coverage reports for the debug build."

    reports {
        xml.required = true
        html.required = true
        csv.required = false
    }

    classDirectories.setFrom(
            fileTree(dir: "${layout.buildDirectory.asFile.get()}/intermediates/javac/debug", exclude: coverageExclusions),
            fileTree(dir: "${layout.buildDirectory.asFile.get()}/tmp/kotlin-classes/debug", exclude: coverageExclusions)
    )

    sourceDirectories.setFrom(
            files(
                    "$projectDir/src/main/java",
                    "$projectDir/src/main/kotlin"
            )
    )

    executionData.setFrom(
            fileTree(dir: layout.buildDirectory.asFile.get(), includes: [
                    "jacoco/testDebugUnitTest.exec",
                    "outputs/unit_test_code_coverage/debugUnitTest/testDebugUnitTest.exec",
                    "outputs/code_coverage/debugAndroidTest/connected/*coverage.ec"
            ])
    )
}
